apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledockerdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SampleDocker
  template:
    metadata:
      labels:
        app: SampleDocker
    spec:
      containers:
      - name: sampledockerrepos
        image: dnazureacr.azurecr.io/sampledockerrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: sampledocker
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: SampleDocker
